### ISSUE TITLE
Contract Licenses

### ISSUE THREAD

**Issue by simonmorley** [the-standard/ibco#106]
Someone please standardise all the contract licenses. 

And someone please discuss what license we should use.

**Comment by simonmorley** [comment]
I still donut know and donut have an answer. What do you think?

**Comment by therealdannzor** [comment]
I vote for a copyleft flavour with much freedom to copy, modify, and distribute. The codebase is not that mature yet so I don't see why we should put too many limitations on it as it is. In the future, this can be re-evaluated.

**Comment by simonmorley** [comment]
Ok, choose one, type it into a PR and ahead we go. It should probably be sorted before next week but it's not life or death.
