### ISSUE TITLE
Think of a better way to store, add, remove bond options in Operator

### ISSUE THREAD

**Issue by ewansheldon** [the-standard/ibco#120]
Currently bond options are essentially indexed by `rate`, this is how we access them and remove them.

This means that if two options have the same rate, we are not able dependably remove one (but not the other).

e.g.
we have a list of rates:
[{
  rate: 2000,
  durationInWeeks: 4
}, {
  rate: 5000,
  durationInWeeks: 4
}, {
  rate: 2000,
  durationInWeeks: 2
}]

if we wanted to remove the third option, we'd have to call `removeRate(2000)`. this would remove the first option first, then we would have to call `removeRate(2000)` again to remove the one we wanted to remove. we would then have to re-add the first option

**Comment by therealdannzor** [comment]
It is a good observation but we should not have bonds that have the same `rate` but different `durationInWeeks`. You are correct in your problem formulation nonetheless.

**Comment by therealdannzor** [comment]
Fixed in https://github.com/the-standard/ibco/pull/141 by only allowing the addition of unique rates
