### ISSUE TITLE
[Discussion] Centralize transfer of rewards

### ISSUE THREAD

**Issue by therealdannzor** [the-standard/ibco#136]
### Background
We currently have to allow Stage 1 and Stage 3 contracts to either mint tokens or transfer from its balance, respectively, in the happy case of a successful exchange or claim:

- **SEuroOffering**: [mint](https://github.com/the-standard/ibco/blob/master/contracts/Stage1/SEuroOffering.sol#L84)
- **Staking**: [transfer](https://github.com/the-standard/ibco/blob/master/contracts/Stage3/Staking.sol#L119)

### Proposal
Store all rewards, whether sEURO or TST, in the Gateway to extend its reach in the [same](https://github.com/the-standard/ibco/blob/master/contracts/Stage2/StandardTokenGateway.sol#L85) way it is being used for rewards in Stage 2. Should we want to keep the minting in Stage 1 at the point of exchange, we can also grant the Gateway this permission instead.

It is worth noting that it could be considered a drawback to have the reward mechanism centralized depending on design philosophy but the proposal argues for that the benefits far exceed the drawbacks. In addition, it also argues for that the Gateway will change less (i.e., require fewer re-deployments) in relation to other contracts.

### API compatability
This will not break any existing public facing APIs as this would simply be a modification of the underlying reward mechanism. Any implementation will take place in a private scope. The Bonding Curve and the bucket mechanism are not affected.

### Cost-benefit analysis
**Pros**:
- remove permission from the SEuroOffering contract to mint sEURO
- no need to supply each Staking contract with sEUROs
- fewer contract balances to keep track of
- only one contract to re-supply and / or manage mint permission

**Cons**:
- if the Gatway is updated, we would need to reconnect all the other contracts
- some increase in Gateway complexity to keep track of different earmarked balances

### Summary
Setting up the IBCO from scratch requires a lot of operations of connecting contracts to one another, setting up permissions, and making sure each contract has enough balance to perform its duties. This proposal could be a good starting point to reduce some of that complexity without compromising on existing security mechanisms or core functionality. In addition, it also opens up for activation and pausing multiple contracts from a single contract interaction, if the Gateway has a more prominent role as a connection hub in the IBCO system. This could reduce some of that overhead burden in the set up phase. Finally, it can also be considered a good foundation for further work that extends beyond the IBCO on-ramp and serve as an interface with other systems.

**Comment by simonmorley** [comment]
Cons: is this really necessary right now?

**Comment by therealdannzor** [comment]
> Cons: is this really necessary right now?

I don't expect this to be implemented in the release but for future reference 😄. It's for the future of the architecture.
