### ISSUE TITLE
IBCO Bug Metamask

### ISSUE THREAD

**Issue by borisnachtsheim** [the-standard/ibco#147]
I just tried the IBCO. First swap of GoerliETH to sEURO was working but then the page didn't update my Eth amount and I could not make a second swap. Page was just hanging.

**Comment by therealdannzor** [comment]
Hey @borisnachtsheim, thanks for filing an issue. Can you be a bit more specific on what happened and what went wrong? As I look into the swap contract, I can see two recent transactions which both were successful:

- [first transaction](https://goerli.etherscan.io/tx/0xca82b57186ade95eacdb4291a4dd1765f8e1e42ca6e61ceded0a1dd9089b537b): 0.1 wETH for 183.5 sEURO
- [second transaction](https://goerli.etherscan.io/tx/0x44b9018f214b18cf969a3b34f89c5b6e08b3cca859cb628ee8d1b94ddf8a1978): 0.02 wETH for 36.7 sEURO

Have you checked your sEURO balance? I can see that you have 302 sEURO now. Let me know what your expectations were 😄

**Comment by therealdannzor** [comment]
Hello @borisnachtsheim, haven't heard anything from you. I will be closing this now but we can re-open it later if you are still facing some issue with it later. Would be thrilled for you to try again! You can find us on Discord if you want to chat more :)
