### ISSUE TITLE
Hard stop and pause contract functionality

### ISSUE THREAD

**Issue by simonmorley** [the-standard/ibco#17]
All main entry contracts should have two functions:

- pause
- hard stop / self destruct

There may be a need to just pause a contract - maybe so we can upgrade a dependancy. A pause would allow and unpause function too.

There may be a need to totally destroy the contract, in which case we should implement something that removes funds (if stored) etc.

**Comment by ewansheldon** [comment]
is this resolved do we think @therealdannzor ?

**Comment by therealdannzor** [comment]
Stage 1 and 2, yes.

Should add to Stage 3 at some point, too.

**Comment by ewansheldon** [comment]
might as well build it in while i'm working on it now?
