### ISSUE TITLE
Solidity / STD Conventions

### ISSUE THREAD

**Issue by simonmorley** [the-standard/ibco#60]
I'd like to propose some conventions around code positioning. 

Right now we have structs and modifiers dotted throughout the code. 

I think it would be tidier and easier to read if we call moved these to the top of the file, like we do with variables etc. 

Struct above the constructor. 

Modifiers immediately below.

Comments welcome!

**Comment by ewansheldon** [comment]
i noticed in the uniswap contracts they put structs [directly above the function they're used in](https://github.com/Uniswap/v3-periphery/blob/main/contracts/interfaces/INonfungiblePositionManager.sol#L79), which i'm not opposed to when the struct is kind of specific to one function or whatever. other than that, agreed 👍🏻

**Comment by simonmorley** [comment]
I saw that.... that's what I wasn't a fan of though.

But actually, it's not uncommon to do that if the struct is JUST for 1 function. 

So how about that then, if it's specific to a function, put it directly above. And if it isn't, put it at the top.

**Comment by therealdannzor** [comment]
We should just decide on a format and then stick to it. Like in Go, they prefer to do what Ewan proposed, to keep the structs close to the implementation.

**Comment by ewansheldon** [comment]
> So how about that then, if it's specific to a function, put it directly above. And if it isn't, put it at the top.

i'm cool with that. i'm fine with whatever rules we set if we're consistent

**Comment by therealdannzor** [comment]
I think it's alright if we make sure to have all the structs in the beginning so we could just scroll through it and get to the "meaty" function. So I'm yay'ing the proposal!

**Comment by therealdannzor** [comment]
To revisit at next project delivery
