### ISSUE TITLE
Staking Interest: a discussion on the way it's applied

### ISSUE THREAD

**Issue by simonmorley** [the-standard/ibco#83]
I've applied the mantra - if it seems to complex, it probably is.

The interest is calculated is pretty basic. There is no APY, APR, just a rate. 

For example, we put in 1,000 TST. On maturity, the user is given the equivalent SEURO plus the interest. That's it. 

A discussion can be had about whether this is the desired solution. And if there's time to find another solution.

**Comment by therealdannzor** [comment]
Replaced by https://github.com/the-standard/ibco/issues/88 which is based on the discussion today
